server:
  port: 8761 # Standard port for Eureka

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false # We are the server, we don't register ourselves
    fetch-registry: false # We don't need to fetch the registry either