version: '3.8'

services:
  # PostgreSQL for Microservices
  postgres:
    image: postgres:15-alpine
    container_name: grocery-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: grocery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: grocery-redis
    ports:
      - "6379:6379"

  # Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: grocery-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: grocery-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data:
