version: '3.8'

services:
  # PostgreSQL for Microservices
  postgres:
    image: postgres:15-alpine
    container_name: grocery-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: grocery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: grocery-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: